"""Shared test fixtures + a reporter that writes tests/results.md on every run.

Design notes
------------
The receptionist's booking logic must survive OpenAI being slow, down, or
returning garbage. So the bulk of this suite runs WITHOUT touching the network:
it exercises the deterministic regex/cleaning layer directly, and for
`analyze_customer_turn` it monkeypatches the OpenAI client to simulate both
malformed responses and hard failures. That keeps the suite free, fast, and
reproducible — the results below come from the same code that runs in prod.

A small optional set marked `live` calls the real API; it's deselected unless
you pass `-m live` with a real OPENAI_API_KEY set.
"""

import os
import datetime as _dt

# A dummy key so `OpenAI(api_key=...)` constructs at import time. No network
# call happens at construction; real calls are monkeypatched in the tests.
os.environ.setdefault("OPENAI_API_KEY", "sk-test-dummy")

# Dummy Twilio + app settings so app.config.settings (a module-level singleton
# built at first import) is fully populated before any test file imports
# anything from app.*. Must live here, not in an individual test file, since
# conftest.py is guaranteed to load first for the whole session.
os.environ.setdefault("TWILIO_AUTH_TOKEN", "test-auth-token-not-a-real-secret")
os.environ.setdefault("TWILIO_ACCOUNT_SID", "ACtestaccountsidnotreal00000000")
os.environ.setdefault("BASE_URL", "http://testserver")
os.environ.setdefault("DATABASE_URL", "sqlite:///./test_twilio_auth.db")

import pytest


class _FakeResponse:
    """Mimics the object returned by client.responses.create()."""
    def __init__(self, text: str):
        self.output_text = text


def make_fake_create(payload: str):
    """Return a stand-in for client.responses.create that yields `payload`."""
    def _create(*args, **kwargs):
        return _FakeResponse(payload)
    return _create


def make_failing_create(exc: Exception):
    """Return a stand-in for client.responses.create that raises `exc`."""
    def _create(*args, **kwargs):
        raise exc
    return _create


@pytest.fixture
def patch_ai(monkeypatch):
    """Patch the module-level OpenAI client's responses.create.

    Usage:
        patch_ai(returns='{"caller_name": "Sam", ...}')   # model returns text
        patch_ai(raises=RuntimeError("boom"))             # model call fails
    """
    from app.services import ai_service

    def _apply(returns: str | None = None, raises: Exception | None = None):
        if raises is not None:
            fake = make_failing_create(raises)
        else:
            fake = make_fake_create(returns if returns is not None else "")
        monkeypatch.setattr(ai_service.client.responses, "create", fake)

    return _apply


# ---------------------------------------------------------------------------
# Results reporter: writes a categorized tests/results.md after the session.
# ---------------------------------------------------------------------------

_CATEGORIES = {
    "conversation": "Conversation edge cases",
    "ambiguous": "Ambiguous bookings",
    "hostile": "Hostile / off-script callers",
    "failure": "Failure injection (OpenAI down / malformed)",
    "live": "Live API integration",
}

# collected per-test outcomes: name -> (category, passed)
_results: dict[str, tuple[str, bool]] = {}


def pytest_runtest_logreport(report):
    if report.when != "call":
        # count setup failures too, but avoid double-counting passes
        if not (report.when == "setup" and report.failed):
            return
    markers = {"conversation", "ambiguous", "hostile", "failure", "live"}
    cat = next((m for m in markers if report.keywords.get(m)), "uncategorized")
    _results[report.nodeid] = (cat, report.passed)


def pytest_sessionfinish(session, exitstatus):
    if not _results:
        return

    by_cat: dict[str, list[bool]] = {}
    for _, (cat, passed) in _results.items():
        by_cat.setdefault(cat, []).append(passed)

    total = len(_results)
    total_passed = sum(1 for _, (_, p) in _results.items() if p)

    lines = []
    lines.append("# Stress-test results")
    lines.append("")
    lines.append(
        f"_Generated by the test suite on "
        f"{_dt.datetime.now().strftime('%Y-%m-%d %H:%M')} — re-run `pytest` to refresh._"
    )
    lines.append("")
    lines.append(f"**Overall: {total_passed}/{total} scenarios passed.**")
    lines.append("")
    lines.append("| Category | Passed | Total |")
    lines.append("| --- | --- | --- |")
    order = ["conversation", "ambiguous", "hostile", "failure", "live", "uncategorized"]
    for cat in order:
        if cat not in by_cat:
            continue
        results = by_cat[cat]
        label = _CATEGORIES.get(cat, "Uncategorized")
        lines.append(f"| {label} | {sum(results)} | {len(results)} |")
    lines.append("")

    failed = [nid for nid, (_, p) in _results.items() if not p]
    if failed:
        lines.append("## Failing scenarios")
        lines.append("")
        for nid in failed:
            lines.append(f"- `{nid}`")
        lines.append("")
    else:
        lines.append("All scenarios passed on the most recent run.")
        lines.append("")

    out_dir = os.path.join(os.path.dirname(__file__))
    with open(os.path.join(out_dir, "results.md"), "w") as f:
        f.write("\n".join(lines))
